### ISSUE TITLE
다음주 월요일까지 MVC 형태로 바꾸기

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#10]
현재 오픈 소스형태를 다음주 화요일전까지 MVC로 전부 바꿔야합니다.

@yhk1515 선배랑 저랑 같이 바꿔야해요.

- 제가 수정하고 선배가 검토하고
- 선배가 수정한거는 제가 검토하고, 하는 형식으로 바꾸죠.

**Comment by dydgns2017** [comment]
@anhive-junior
정상 동작하지 않는 USBlist.php 기능 부분은 제외하겠습니다.

**Comment by dydgns2017** [comment]
@anhive-junior

[이 링크 부분 ](https://github.com/anhive-junior/smart-board/commit/431ed2962a92cc2ccde0790d357e67b48d2cfcd4) 확인해주시면 감사하겠습니다 :D

**Comment by dydgns2017** [comment]
@anhive-junior

![image](https://user-images.githubusercontent.com/36920367/60459424-214bbc00-9c7c-11e9-9270-53bd9a27709d.png)
![image](https://user-images.githubusercontent.com/36920367/60459439-26a90680-9c7c-11e9-9ac1-abbaf92274c8.png)

/var/www 에 있는 tasks 파일은 밑에 makefile에 의해서 생성됩니다. 어떤 의도로 생성되는지 잘 모르겠습니다. 다른 오류 찾다가 /var/www/ 디렉토리에서 해당 파일만 소프트 링크가 정상적으로 걸리지 않은 상태라서 발견하게 되었습니다.

> grep -nr tasks .installer/core/scheduler/Makefile
14:     mkdir -p /etc/hive/tasks
15:     touch /etc/hive/tasks/schedule.tasks
16:     chown www-data:www-data /etc/hive/tasks/schedule.tasks
17:     ln -sf ./www /var/www/tasks
22:      tar -cvf www/timework.core.tar.gz res/* tasks/* timeworks timeworks.c Makefile

**Comment by ilovecho** [comment]
timework는 mvc와 다른 이슈로 등록해 주세요

timework은 crontab을 대신하여 초단위로 작업을 처리할 수 있도록 만들었던 프로그램입니다.
php에서 작업지시를 하면 timework이 작업을 실행하는 구조라고 알고 있습니다.
구체적인 내용은 코드를 확인할 필요가 있습니다.

**Comment by dydgns2017** [comment]
@yhk1515 
현재 MVC 모델 안한거 체크해야하는데 어디까지 하셨나요?

**Comment by dydgns2017** [comment]
## 오류 동작이 있어서 예외처리하여 만든 프로그램 항목들
> 이 부분은 코드를 손보는 것보다 전체적으로 합치거나 바꿔주는 편이 낫다고 봄.
- samwork.html : 앨범관리
- playwork.html : 재생관리
- syswork.html   : 접속관리


## MVC 모델 제외된 프로그램 항목들
- checker.php - 프로그램 검증 솔루션
- USBlist.php - USB로 사진 옮기는 프로그램

## 어디서 사용되는지 모르는 프로그램 항목들
- listvideos .html .php
- listphotos .html .php
- openvideo .html .php
