### ISSUE TITLE
디코딩시 코드 들여쓰기 버그

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#12]
> 제 PC에서 코드 들여쓰기 한 후, 다른 PC에서 소스 코드를 다운로드 받으면 들여쓰기 디코딩시에 깨지는(일정하지 않은 들여쓰기) 형식의 버그가 발생합니다. 

@anhive-junior

소스 코드를 다운로드 받고 디코딩시에 들여쓰기 버그가 일어나지 않도록 space 만 이용하여 들여쓰기를 사용합시다. 혹시 다른 아이디어가 있으면 알려주세요 😃

**Comment by ilovecho** [comment]
"#14 코드 들여쓰기 점검 필요" 참조
