### ISSUE TITLE
Raspbian Buster 테스트

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#13]
@anhive-junior

6월20일
라즈베리파이 4가 나오면서 라즈비안 베이스가 stretch에서 debian buster로 변경되었습니다.
smart-board를 적용하였을 시 정상적으로 동작하는지 테스트해야합니다.

![image](https://user-images.githubusercontent.com/36920367/60046132-93168980-9701-11e9-95ae-28d41c3084ca.png)

업데이트 핵심 이슈는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/36920367/60046372-264fbf00-9702-11e9-908b-e631b544ea1d.png)

> RFKill은 리눅스 커널의 서브시스템으로 컴퓨터의 전파 송수신 장치들에 대해 질의하고, 활성화하고, 비활성화 할 수 있도록 해주는 인터페이스를 제공합니다. 송수신 장치가 비활성화되는 경우, 소프트웨어가 그 장치를 재활성화 시킬수 있는 상태(소프트 블럭(soft block))나 소프트웨어로는 그 장치를 재활성화 시킬 수 없는 상태(하드 블럭(hard block)) 중 하나로 장치의 상태가 변화됩니다. ( 참조 링크 : https://access.redhat.com/documentation/ko-kr/red_hat_enterprise_linux/6/html/power_management_guide/rfkill )

라즈베리파이 부팅시 및 사용시에 많은 유저들이 wifi가 하드블록 또는 소프트 블록되어 있는 현상때문에. rfkill unblock wifi  명령어가 기본적으로 실행되게 만들었습니다. rfkill 에서 옵션 unblock은 특정 장치를 enable 하는 것과 같습니다.

**Comment by dydgns2017** [comment]
![image](https://user-images.githubusercontent.com/36920367/60095872-943fc900-978a-11e9-9767-249fc28561b6.png)

**Comment by dydgns2017** [comment]
sudo apt-get install -y php

[PHP : 어플리케이션 서버 설치](https://github.com/anhive-junior/smart-board/wiki/Install-Smart-Board#53-php--%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EC%84%9C%EB%B2%84-%EC%84%A4%EC%B9%98)시에 php 7.0 이 아니라 7.1와 7.3이 동시에 다운로드가 되며 7.0 디렉토리가 아니라 7.3와 7.1 디렉토리가 생성됨. PHP 서버 운영 환경 설정시 다음과 같은 오류가 발생,

> sed: can't read /etc/php/7.0/apache2/php.ini: No such file or directory

이후에 다음과 같이 해결한 후 wiki 수정

```
#set for file transfer bigger then 2M
phpini="/etc/php/7.0/apache2/php.ini"
[ ! -f "$phpini" ] && phpini="/etc/php/7.3/apache2/php.ini"
sudo sed -i 's/post_max_size = .M/post_max_size = 2G/' $phpini
grep "post_max_size =" $phpini
sudo sed -i 's/upload_max_filesize = .M/upload_max_filesize = 2G/' $phpini
grep "upload_max_filesize =" $phpini
# end of script
```

**Comment by dydgns2017** [comment]
+ 추가적으로 현재 제 라즈베리파이는 와이파이 모듈이 고장나서 ap 프로세스에 대한 동작에 대한 테스트를 완료하지 못합니다. ap 테스트는 사무실에서 다른 라즈베리파이를 이용하거나 혹은 다른 분이 테스트해야합니다.

- 현재 ap 기능 제외하고 정상적으로 설치가 되며, 오작동하는 부분은 없습니다.
- VNC는 HDMI가 연결되어있는 상태에서 동작되게 소프트웨어가 변경되었습니다.
- samba 패키지 프로그램이 업그레이드 되었습니다. 설치시에 유틸리티 설정에 대해서 묻습니다.

@anhive-junior

**Comment by ilovecho** [comment]
> sudo apt-get install -y php
> 
> [PHP : 어플리케이션 서버 설치](https://github.com/anhive-junior/smart-board/wiki/Install-Smart-Board#53-php--%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EC%84%9C%EB%B2%84-%EC%84%A4%EC%B9%98)시에 php 7.0 이 아니라 7.1와 7.3이 동시에 다운로드가 되며 7.0 디렉토리가 아니라 7.3와 7.1 디렉토리가 생성됨. PHP 서버 운영 환경 설정시 다음과 같은 오류가 발생,
> 
> > sed: can't read /etc/php/7.0/apache2/php.ini: No such file or directory
> 
> 이후에 다음과 같이 해결한 후 wiki 수정
> 
> ```
> #set for file transfer bigger then 2M
> phpini="/etc/php/7.0/apache2/php.ini"
> [ ! -f "$phpini" ] && phpini="/etc/php/7.3/apache2/php.ini"
> sudo sed -i 's/post_max_size = .M/post_max_size = 2G/' $phpini
> grep "post_max_size =" $phpini
> sudo sed -i 's/upload_max_filesize = .M/upload_max_filesize = 2G/' $phpini
> grep "upload_max_filesize =" $phpini
> # end of script
> ```
만일 /etc/php 밑에 php.ini가 하나만 있다면
phpini=$(find /etc/php -name php.ini)
로 지정하면 좀더 간단하지 않을까 함.

**Comment by dydgns2017** [comment]
![image](https://user-images.githubusercontent.com/36920367/60158309-ca815500-982b-11e9-80a2-f476b89def0a.png)
2개의 ini 파일이 존재합니다. 피드백 주신대로
> phpini=$(find /etc/php/*/apache2 -name php.ini)

와일드 카드를 이용하여 위와 같이 변경하였습니다. ( github 위키에도 적용하였음. )

![image](https://user-images.githubusercontent.com/36920367/60158459-2055fd00-982c-11e9-8b88-0bb071493161.png)

**Comment by dydgns2017** [comment]
-debian buster 테스트 결과-
ap 설정에 대해서 다음과 같이 동작하는 것을 확인할 수 있었습니다.
