### ISSUE TITLE
코드 들여쓰기 점검 필요

### ISSUE THREAD

**Issue by ilovecho** [anhive-junior/smart-board#14]
github으로 소스를 보면 들여쓰기기 일정하지 않습니다.
통일된 형식으로 볼 수 있도록 4자 들여쓰기를 맞추고, 
TAB은 사용하지 않는 것으로 합니다.

다음 명령을 사용하면 탭을 일괄적으로 "    "4개 스페이스로 변경합니다.
sed -i 's/\t/    /g' $(find . -name "*.html")
sed -i 's/\t/    /g' $(find . -name "*.php")

**Comment by dydgns2017** [comment]
@ilovecho 
피드백 감사합니다. 오늘 밤에 전체적인 들여쓰기를 수정하겠습니다 :D

**Comment by ilovecho** [comment]
코드를 살펴보면 인덴트가 4개 스페이스로 구성되어 있지 않음. 다시 수정 필요합니다.

sed를 다시 사용법을 표시합니다. 
<pre>
sed -i 's/\t/    /g' $(find . -name "*.html")
sed -i 's/\t/    /g' $(find . -name "*.php")
</pre>
"\t"(탭)을 "____"(스페이스 4개)로 바꾸는 작업입니다.

좋은하루되세요

**Comment by dydgns2017** [comment]
https://prettier.io/ -- @toriato 토리아토가 준 방법입니다.
이 방법을 적용해보도록 하겠습니다.

--- prettier.io 방법 말고 위의 알려준 방법으로 코드 스타일을 변경하였습니다.
