### ISSUE TITLE
프로그램 변경에 따른 위키 수정이 필요함

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#18]
@anhive-junior
rmtrack, cutconnect 등 여러 프로그램이 삭제되고 변경되었음에 따라서 위키를 수정해야함,

**Comment by ilovecho** [comment]
그럼 종속포털에 관련한 부분을 제외하려면 
wiki에서 "종속포털 접속 네트워크 관리"와 관련되어 있습니다.

**Comment by dydgns2017** [comment]
@anhive-junior

변경완료
