### ISSUE TITLE
사진 등록 웹화면이 사파리가 크롬과 달리 나타남.

### ISSUE THREAD

**Issue by ilovecho** [anhive-junior/smart-board#22]
노트북 사파리에선 위치가 정렬되어 있지 않고, 
아이폰에선 아이콘만 크게 나타나 등록 할 수 없음.

**Comment by yhk1515** [comment]
signage.base.css 에 지정한 css 값을 첫 로딩시 못가지고 오는 문제가 있어 html 태그에 직접 스타일 속성을 달아서 해결하였음.
