### ISSUE TITLE
웹 목록편집 화면에서 실수로 사진삭제가 눌리면 모든 사진이 삭제됨

### ISSUE THREAD

**Issue by ilovecho** [anhive-junior/smart-board#23]
실수로 사진삭제 버튼이 눌리고 모든 사진이 삭제됨
사진 삭제 처리 진행하기 전에 confirm화면 필요

**Comment by dydgns2017** [comment]
![image](https://user-images.githubusercontent.com/36920367/61769910-d65e3800-ae26-11e9-8559-0849ead8aeeb.png)

수정 완료
