### ISSUE TITLE
로그인 화면 아이콘 문제

### ISSUE THREAD

**Issue by ilovecho** [anhive-junior/smart-board#25]
![Screenshot_20190718-030316_Chrome](https://user-images.githubusercontent.com/2391906/61400013-4ee66580-a90a-11e9-909d-0f39be14fee6.jpg)

**Comment by ilovecho** [comment]
안드로이드 앱 크롬브라우저
아이폰 사파리 브라우저에서도 동일한 현상 발생
*  wiki의 설치과정에 따름

**Comment by yhk1515** [comment]
@anhive-junior
signage.base.css 에 지정한 css 값을 첫 로딩시 못가지고 오는 문제가 있어 html 태그에 직접 스타일 속성을 달아서 해결하였음.
