### ISSUE TITLE
보안 코드 수정 요청

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#26]
@yhk1515 

https://github.com/anhive-junior/smart-board/blob/8629e0b61e74daf05da97be77a0a129248e81f62/s00_signage.php#L2036-L2039

```
if ( in_array($func, $security) && $_SESSION['uselevel']<2 )
	outputJSON("사용자 권한이 없습니다", "success");
```

위의 코드 형식으로 바꿔주시는걸 검토해주시길 바람.

in_array에 대해서 모르는 경우 밑의 예제 코드를 참고하길 바람.
https://www.w3schools.com/php/showphp.asp?filename=demo_func_in_array

**Comment by yhk1515** [comment]
수정완료
