### ISSUE TITLE
timework와 task 프로그램 재점검

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#29]
#15 이슈 다시 한 번 확인하기.

timeworks 서비스의 동작방식에 대해서 이해하고 #15 에서의 프로그램과 연관이 있으면 해당 프로그램을 다시 살려놓을지도 생각해봐야함.

**Comment by dydgns2017** [comment]
```
.installer/core/scheduler/Makefile_centos:16:   mkdir -p /etc/hive/tasks
.installer/core/scheduler/Makefile_centos:17:   touch /etc/hive/tasks/schedule.tasks
.installer/core/scheduler/Makefile_centos:18:   chown apache:apache /etc/hive/tasks/schedule.tasks
.installer/core/scheduler/Makefile_centos:20:   -sudo rm /var/www/html/tasks
.installer/core/scheduler/Makefile_centos:21:   sudo ln -s ${CURDIR}/www /var/www/html/tasks
```

grep으로 파일 내용들을 확인한 결과 Makefile_centos에서도 task 프로그램을 사용하기 위한 것 같음.
CentOS 전용버전임, 이에 대해서 정확한 정보가 없음.

**Comment by dydgns2017** [comment]
@anhive-junior
이 부분에 대해서 금요일날 회의때 scheduler 동작방식과 timework 데몬 task 연관 관계에 대해서 학습이 필요하다고 생각됨.

**Comment by ilovecho** [comment]
스케줄러는 초단위로 작업을 처리할 수 있도록 하고자 해서 만든 데몬 프로그램입니다.
요청한 작업을 시간에 맞춰 shell script를 실행해 주는 것으로 
그동안 Ubuntu, SentOS, Pi에서 활용되었습니다.

스마트게시판에서 슬라이드쇼 목록 관리에 활용하고 있습니다.
