### ISSUE TITLE
install_stretch.sh  - step.7 install error!

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#4]
![image](https://user-images.githubusercontent.com/36920367/57965831-883f3b00-7984-11e9-8ea0-25acc1abab8e.png)

**Comment by dydgns2017** [comment]
0.0.18 으로 수정 후,

![image](https://user-images.githubusercontent.com/36920367/57967675-c8121c80-799c-11e9-9ea9-5bf2d56cf76e.png)

설치 시 
is up to date --
후에 
timeworks와 rinputd 프로그램이 failed not loaded가 뜨지만 모든 프로그램 설치 이후 reboot 시에

systemctl status rinput
![image](https://user-images.githubusercontent.com/36920367/57967702-16272000-799d-11e9-9be2-e56740a5e995.png)

systemctl status timeworks
![image](https://user-images.githubusercontent.com/36920367/57967706-23dca580-799d-11e9-99ca-6087d0cde10e.png)

데몬들이 정상적으로 동작하여 문제 없다고 판단함.

**Comment by ilovecho** [comment]
처음 오류가 있지만 두번째 동작에서 정상적으로 동작 하는데
나중에 시간이 된다면 처음 동작에서도 동작될 수 있도록 수정해 봅시다.

**Comment by dydgns2017** [comment]
@ilovecho  넵 감사합니다.

**Comment by yhk1515** [comment]
@ilovecho  넵 확인했습니당

**Comment by dydgns2017** [comment]
rinput, timeworks 리다이렉션으로 make install 시 나오는 에러 메세지 dev null로 버리기,
