### ISSUE TITLE
piwizard 프로그램 disable 방법

### ISSUE THREAD

**Issue by dydgns2017** [anhive-junior/smart-board#6]
https://www.raspberrypi.org/forums/viewtopic.php?t=231557

**Comment by ilovecho** [comment]
생각보다 여러 문제가 있군요
원격로그인하면서 발생하는 경우 저거하는 것을 목적으로한다면 
특히, 사진앞에 나타나는 경우라면 이를 해결할 수 있도록 할 필요가 있군!

sudo rm /etc/xdg/autostart/piwiz.desktop
sudo reboot now

그런데 내가 경험하는 문제의 핵심은 처음 시작하는 사람은
열심히 한글로 설정하다보면 한글 폰트가 없어서 오류가 난다는 것
그리고 한국으로 와파이설정시 와이파이가 제대로 올라오지 않는 것 
이 두 문제가 생기기 때문에 

> 편의를 제공할 수 있도록 했지만 오히려 장애를 일으키는 요소

가 되었다는 점이
해결할 수 있는 방법을 찾자는 의미입니다.

**Comment by dydgns2017** [comment]
@ilovecho 
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=230332&p=1412094#p1412094
예전에 라즈베리파이 커뮤니티에 올렸던 글인데 해당 글에서 살펴보면

"It looks as if there is a problem with the settings for Korea in the firmware for our wi-fi hardware - we've notified the manufacturer and will get a fix out as soon as they provide one. Thanks for bringing it to our attention."

라즈베리파이에서의 와이파이 하드웨어에 문제가 있어서 이것을 알려서 수정한다고 답글을 주긴 했는데 아직 수정이 안된듯 합니다... 아무래도 라즈베리파이 재단에서 이 문제를 관심있게 봐주지 않는다면 오랜 기간동안 이 문제가 지속될 경우가 크다고 보고 있습니다. 계속해서 해당 커뮤니티에다가 글을 올려서 언제쯤 해결되는지 물어볼까요?

**Comment by ilovecho** [comment]
wizard는 한글폰트가 없어서 locale을 한글로 설정하는 경우도 복구 불가능한 상태가 됨으로 이 것도 함께 구체적으로 확인하여 다시 문의할 수 있도록 하는 것을 어떨지... 아님 문제를 찾아 해결 방법을 제시해 보는 것은 어떨지...한글 문제 한국인이 해결해야 하지 않을까 ... ㅋㅋ

**Comment by dydgns2017** [comment]
@ilovecho 그러면 wizard를 실행시키기 전에 한글폰트를 설치하여야하는데, 라즈베리파이에 기본적으로 한글폰트가 깔려있지 않았으니 추가적으로 라즈비안 재단에다가 폰트를 미리 설치해주라고 말해볼까요?

**Comment by dydgns2017** [comment]
@dydgns2017 

> 편의를 제공할 수 있도록 했지만 오히려 장애를 일으키는 요소

1. 한글폰트가 적용되지 않아서 locale을 변경하였을텐데 폰트가 보이지 않는 불편함
2. 한국 와이파이로 잡을 때 와이파이가 동작되지 않는 문제점
